# Generated by Django 3.0.7 on 2020-06-24 02:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LogicConnector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('label', models.CharField(max_length=100, verbose_name='Label')),
                ('run_cnt', models.PositiveIntegerField(default=0, verbose_name='Run Count')),
                ('business_logic', models.TextField(verbose_name='Business Logic(Python code)')),
            ],
            options={
                'verbose_name': 'Logic Connector',
                'verbose_name_plural': 'Logic Connectors',
            },
        ),
        migrations.CreateModel(
            name='PredictionServer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100, verbose_name='Label')),
                ('server_url', models.URLField(verbose_name='Server URL')),
                ('datarobot_key', models.CharField(max_length=100, verbose_name='DR Key')),
                ('datarobot_username', models.CharField(max_length=100, verbose_name='DR Username ')),
                ('api_token', models.CharField(max_length=100, verbose_name='API Token')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('logic_connector', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='datarobotapiwrapper.LogicConnector', verbose_name='Default Logic Connector')),
            ],
            options={
                'verbose_name': 'Prediction Server',
                'verbose_name_plural': 'Prediction Servers',
            },
        ),
        migrations.CreateModel(
            name='LogFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('s3_bucket', models.TextField()),
                ('s3_key', models.TextField()),
                ('logic_connector', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='datarobotapiwrapper.LogicConnector', verbose_name='Logic Connector')),
            ],
            options={
                'verbose_name': 'Log file',
                'verbose_name_plural': 'Log files',
            },
        ),
        migrations.CreateModel(
            name='BusinessEntity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='Unique Business Entity Name')),
                ('logic_connector', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='datarobotapiwrapper.LogicConnector', verbose_name='Logic Connector')),
            ],
        ),
    ]
